export const PACKAGE_DETAILS_REQUEST= 'PACKAGE_DETAILS_REQUEST'
export const PACKAGE_DETAILS_SUCCESS= 'PACKAGE_DETAILS_SUCCESS'
export const PACKAGE_DETAILS_FAIL= 'PACKAGE_DETAILS_FAIL'

export const PACKAGE_DELETE_REQUEST= 'PACKAGE_DELETE_REQUEST'
export const PACKAGE_DELETE_SUCCESS= 'PACKAGE_DELETE_SUCCESS'
export const PACKAGE_DELETE_FAIL= 'PACKAGE_DELETE_FAIL'

export const PACKAGE_CREATE_REQUEST= 'PACKAGE_CREATE_REQUEST'
export const PACKAGE_CREATE_SUCCESS= 'PACKAGE_CREATE_SUCCESS'
export const PACKAGE_CREATE_FAIL= 'PACKAGE_CREATE_FAIL'
export const PACKAGE_CREATE_RESET= 'PACKAGE_CREATE_RESET'

export const PACKAGE_UPDATE_REQUEST = 'PACKAGE_UPDATE_REQUEST'
export const PACKAGE_UPDATE_SUCCESS = 'PACKAGE_UPDATE_SUCCESS'
export const PACKAGE_UPDATE_FAIL = 'PACKAGE_UPDATE_FAIL'
export const PACKAGE_UPDATE_RESET = 'PACKAGE_UPDATE_RESET'

export const PACKAGE_ID_DETAILS_REQUEST= 'PACKAGE_ID_DETAILS_REQUEST'
export const PACKAGE_ID_DETAILS_SUCCESS= 'PACKAGE_ID_DETAILS_SUCCESS'
export const PACKAGE_ID_DETAILS_FAIL= 'PACKAGE_ID_DETAILS_FAIL'