export const SUBSCRIBE_CREATE_REQUEST = 'SUBSCRIBE_CREATE_REQUEST'
export const SUBSCRIBE_CREATE_SUCCESS = 'SUBSCRIBE_CREATE_SUCCESS'
export const SUBSCRIBE_CREATE_FAIL = 'SUBSCRIBE_CREATE_FAIL'
export const SUBSCRIBE_CREATE_RESET = 'SUBSCRIBE_CREATE_RESET'

