export const SUBSCRIBE_CREATE_REQUEST = 'SUBSCRIBE_CREATE_REQUEST'
export const SUBSCRIBE_CREATE_SUCCESS = 'SUBSCRIBE_CREATE_SUCCESS'
export const SUBSCRIBE_CREATE_FAIL = 'SUBSCRIBE_CREATE_FAIL'
export const SUBSCRIBE_CREATE_RESET = 'SUBSCRIBE_CREATE_RESET'

export const SUBSCRIBE_DETAILS_REQUEST= 'SUBSCRIBE_DETAILS_REQUEST'
export const SUBSCRIBE_DETAILS_SUCCESS= 'SUBSCRIBE_DETAILS_SUCCESS'
export const SUBSCRIBE_DETAILS_FAIL= 'SUBSCRIBE_DETAILS_FAIL'