export const TODO_CREATE_REQUEST = 'TODO_CREATE_REQUEST'
export const TODO_CREATE_SUCCESS = 'TODO_CREATE_SUCCESS'
export const TODO_CREATE_FAIL = 'TODO_CREATE_FAIL'
export const TODO_CREATE_RESET = 'TODO_CREATE_RESET'

export const TODO_DETAILS_REQUEST= 'TODO_DETAILS_REQUEST'
export const TODO_DETAILS_SUCCESS= 'TODO_DETAILS_SUCCESS'
export const TODO_DETAILS_FAIL= 'TODO_DETAILS_FAIL'

export const TODO_DELETE_REQUEST= 'TODO_DELETE_REQUEST'
export const TODO_DELETE_SUCCESS= 'TODO_DELETE_SUCCESS'
export const TODO_DELETE_FAIL= 'TODO_DELETE_FAIL'