# Generated by Django 3.2.5 on 2021-07-14 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todoclass',
            name='completetime',
        ),
        migrations.RemoveField(
            model_name='todoclass',
            name='important',
        ),
    ]
